[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
itertools = "0.12.0"
log = "0.4.20"
nom = "7.1.3"
once_cell = "1.18.0"
pretty_env_logger = "0.5.0"
regex = "1.10.2"
