[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
itertools = "0.12.0"
log = "0.4.17"
once_cell = "1.16.0"
pretty_env_logger = "0.5.0"
regex = "1.7.0"
