[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
log = "0.4.22"
nom = "7.1.3"
pretty_env_logger = "0.5.0"
regex = "1.11.1"
